# Generated by Django 4.2.6 on 2023-10-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About_As',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=255, null=True, verbose_name='Заголовок')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'О нас',
                'verbose_name_plural': 'О нас',
            },
        ),
        migrations.CreateModel(
            name='FeedBack',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fio', models.CharField(max_length=155, verbose_name='ФИО')),
                ('email', models.EmailField(blank=True, max_length=155, null=True, verbose_name='Email')),
                ('number', models.IntegerField(blank=True, null=True, verbose_name='Номер телефона')),
                ('theme', models.CharField(blank=True, choices=[('Cargo', 'Карго'), ('Forwarding', 'Пересылка')], default=('Cargo', 'Карго'), max_length=10, null=True, verbose_name='Выборка')),
                ('title', models.CharField(blank=True, help_text='Макс. символов 500', max_length=500, null=True, verbose_name='Тема')),
                ('description', models.CharField(blank=True, help_text='Макс. символов 500', max_length=500, null=True, verbose_name='Обращение')),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратные связи',
            },
        ),
    ]
